### ISSUE TITLE
The zookeeper.connect-string attribute does not take effect after the change

### ISSUE THREAD

**Issue by dANGsx** [spring-cloud/spring-cloud-zookeeper#130]
I need to change this property : `spring.cloud.zookeeper.connect-string` property, But it's not working .
I opened two zookeeper: 2181 and 2182, Always on the Port 2181.
```
application.yml
spring:
  cloud:
    zookeeper:
      connect-string: localhost:2182
      discovery:
        root: /zktest
  application:
    name: zkTest
server:
  port: 8080
```
```
ZkApplication
@SpringBootApplication
@EnableDiscoveryClient
public class ZkApplication {
    public static void main(String[] args) {
        SpringApplication.run(ZkApplication.class, args);
    }
}
```
