### ISSUE TITLE
Invalid StubConfiguration created basing on dependency path

### ISSUE THREAD

**Issue by adrian-wozniak** [spring-cloud/spring-cloud-zookeeper#138]
Given: Dependency configuration in boostrap.yml:
```
spring.cloud.zookeeper:
  dependencies:
    some-service:
      path: io/company/department/some-service
```

When: Getting stubs configuration
```
@Autowired
ZookeeperDependencies zookeeperDependencies;

StubsConfiguration someServiceStub = zookeeperDependencies
    .getDependencyForAlias("some-service")
    .getStubsConfiguration();
```

Then:
```
"io".equals(someServiceStub.getStubsGroupId())
"company".equals(someServiceStub.getStubsArtifactId())
"stubs".equals(someServiceStub.getStubsClassifier())
```

Expected:
```
"io.company.department".equals(someServiceStub.getStubsGroupId())
"some-service".equals(someServiceStub.getStubsArtifactId())
"stubs".equals(someServiceStub.getStubsClassifier())
```
