### ISSUE TITLE
loadBalancerType=RANDOM not applied

### ISSUE THREAD

**Issue by wyzssw** [spring-cloud/spring-cloud-zookeeper#143]
I use application.properties with :
```
spring.cloud.zookeeper.connect-string=127.0.0.1:2181
spring.cloud.zookeeper.dependency.ribbon.enabled=true
spring.cloud.zookeeper.dependencies.user_service.loadBalancerType=RANDOM

```
but finnaly loadbalanceRule is `roundRobinRule` which in `com.netflix.loadbalancer.AvailabilityFilteringRule.choose(Object)`
it use always "default" not `user_service`

```
protected Server getServer(ILoadBalancer loadBalancer) {
		if (loadBalancer == null) {
			return null;
		}
		return loadBalancer.chooseServer("default"); // TODO: better handling of key
	}
```

with
spring boot:1.4.3.RELEASE
spring-cloud-dependencies:Brixton.SR5

```
<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-zookeeper-all</artifactId>
		</dependency>
```

**Comment by spencergibb** [comment]
Please upgrade to the latest Camden or Dalston SR and try again. See https://spring.io/blog/2017/07/21/spring-cloud-dalston-sr2-is-available-now#end-of-life-for-angel-and-brixton-release-trains

**Comment by wyzssw** [comment]
I upload a sample project with `spring cloud:Dalston.SR2` and `spring boot:1.5.6.RELEASE`
at https://github.com/wyzssw/spring-zk-sample

application.properties
```
server.port=8080
spring.application.name=user


spring.cloud.zookeeper.connect-string=127.0.0.1:2181
spring.cloud.zookeeper.dependency.ribbon.enabled=true
spring.cloud.zookeeper.dependencies.user.loadBalancerType=RANDOM
```

SpringZkSampleApplication.java
```
@SpringBootApplication
@EnableDiscoveryClient
@RestController
public class SpringZkSampleApplication {
  
  @Autowired
  private RestTemplate restTemplate;

  public static void main(String[] args) {
    SpringApplication.run(SpringZkSampleApplication.class, args);
  }
  
  @RequestMapping("/home")
  public String home() {
    return "Hello World";
  }
  
  @RequestMapping("/")
  public String goHome() {
    System.out.println(restTemplate.getForObject("http://user/home", String.class));
    return "Go home";
  }
  
}
```


`spring.cloud.zookeeper.dependencies.user.loadBalancerType=RANDOM`
is not work, ervery time it choose server by `om.netflix.loadbalancer.AvailabilityFilteringRule.choose(Object)` which always use roundRobinRule

**Comment by spencergibb** [comment]
You don't define any dependencies. If you run with `-debug` or look at `/autoconfig` you'll likely see something like "No dependencies have been passed for the service" or "Dependencies are not defined in configuration, but switch is turned on"

You probably need `spring.cloud.zookeeper.dependency.enabled=true` and `spring.cloud.zookeeper.dependencies.*` set.

**Comment by wyzssw** [comment]
I have already define the `spring.cloud.zookeeper.dependencies.user.loadBalancerType=RANDOM`

and http://localhost:8080/autoconfig
return 

![image](https://user-images.githubusercontent.com/4242774/29359442-4932c10a-82b1-11e7-8e97-713dd0415248.png)

**Comment by spencergibb** [comment]
please don't post screenshots.

You didn't define any dependencies. See https://github.com/spring-cloud/spring-cloud-zookeeper/blob/master/docs/src/main/asciidoc/spring-cloud-zookeeper.adoc#setting-up-zookeeper-dependencies

**Comment by wyzssw** [comment]
I am sorry i didn't understand
The project `https://github.com/wyzssw/spring-zk-sample`  only depend itself ,is config
`spring.cloud.zookeeper.dependencies.user.loadBalancerType=RANDOM`
can not decare a dependency?
must define `path` 、`stub` or anything else？or must with yml not properties file

**Comment by spencergibb** [comment]
the `spring.cloud.zookeeper.dependencies.user.loadBalancerType=RANDOM` will only work if you are using the dependencies feature as a linked to in the docs

```
spring.cloud.zookeeper:
  dependencies:
    newsletter:
      path: /path/where/newsletter/has/registered/in/zookeeper
      loadBalancerType: ROUND_ROBIN
      contentTypeTemplate: application/vnd.newsletter.$version+json
      version: v1
      headers:
        header1:
            - value1
        header2:
            - value2
      required: false
      stubs: org.springframework:foo:stubs
    mailing:
      path: /path/where/mailing/has/registered/in/zookeeper
      loadBalancerType: ROUND_ROBIN
      contentTypeTemplate: application/vnd.mailing.$version+json
      version: v1
      required: true
```

Otherwise see http://cloud.spring.io/spring-cloud-static/Dalston.SR2/#_customizing_the_ribbon_client for how to customize ribbon.
