### ISSUE TITLE
SSL does not work with random ports

### ISSUE THREAD

**Issue by mbhuie** [spring-cloud/spring-cloud-zookeeper#150]
Given Service provider configuration

```
 server:
   port: 0
   ssl:
     client-auth: need
     enabled: true
     key-store: server.jks
     key-store-password: secret
     key-password: secret
 
 spring:
   application.name: service-provider
   cloud:
     zookeeper:
       discovery:
         enabled: true
   
 security:
   basic:
     enabled: false
```

The client is unable to detect the service. #132 

While if the ports are fixed e.g.
```
server:
  port: 9010
  ssl:
    client-auth: need
    enabled: true
    key-store: server.jks
    key-store-password: secret
    key-password: secret

spring:
  application.name: service-provider
  cloud:
    zookeeper:
      discovery:
        enabled: true
        instance-ssl-port: 9010
  
security:
  basic:
    enabled: false
```
It works!

This leads to tight port bindings and make it less flexible to start multiple instance of service-provider application without worrying about ports.

Can it be derived from 

> server.port: 0
and
> server.ssl.enabled : true

instead of 
> spring.cloud.zookeeper.discovery.instance-ssl-port
