### ISSUE TITLE
Thrown "KeeperErrorCode = Unimplemented for /services" exception

### ISSUE THREAD

**Issue by kdyzm** [spring-cloud/spring-cloud-zookeeper#173]
I used the "SPRING INITIALIZR" tool to generate a simple project that contained the "Zookeeper Discovery" and "Web" dependencies. I just added the zookeeper's connection configuration information, and then I ran the program. Finally, the startup failed. It throws the following exception:
"**org.apache.zookeeper.KeeperException$UnimplementedException: KeeperErrorCode = Unimplemented for /services/server1/2f35091a-bd8a-4701-993e-b10dd9dc19b2**".
Below is the profile I added：
``` yml
server:
  port: 8989

spring:
  application:
    name: server1
  cloud:
    zookeeper:
      enabled: true
      connect-string: 127.0.0.1:2181
```

What am I doing wrong?
![image](https://user-images.githubusercontent.com/12097910/41510559-537ad49e-7299-11e8-99ae-1eda21e8080f.png)
