### ISSUE TITLE
how can the app register with host ip to zookeeper?

### ISSUE THREAD

**Issue by weilinqwe** [spring-cloud/spring-cloud-zookeeper#184]
I use spring-cloud-starter-zookeeper-discovery:2.0.0.RELEASE to register app in zookeeper. I deploy the app in k8s, it seems that the app register with hostname in zookeeper(default way), but the client accessing the app outside the k8s cannot resolve the hostname in k8s. so how can the app register with host ip in zookeeper?

**Comment by spencergibb** [comment]
Set `spring.cloud.zookeeper.discovery.prefer-ip-address=true` to use an ip.

The spring-cloud-commons project does it's best to guess which ip/hostname to use. 

See https://cloud.spring.io/spring-cloud-static/Finchley.SR2/single/spring-cloud.html#ignore-network-interfaces for information on how to inform the guessing by ignoring or preferring certain networks.

**Comment by weilinqwe** [comment]
it works!!!! thanks a lot. 
the config is:
```
server:
  port: 8081
spring:
  application:
    name: TacoCloud
  cloud:
    zookeeper:
      connect-string: 192.168.11.89:2181
      discovery:
        register: true
        prefer-ip-address: true     
    inetutils:
      preferred-networks:
      - 192.168
      - 172.20    
```
after deployed in k8s, it register ip in zookeeper:
```

  | {"name":"TacoCloud","id":"950ec741-5247-4452-92fa-13b99434c9ae","address":"172.20.64.201","port":8081,"sslPort":null,"payload":{"@class":"org.springframework.cloud.zookeeper.discovery.ZookeeperInstance","id":"application-1","name":"TacoCloud","metadata":{}},"registrationTimeUTC":1543820989566,"serviceType":"DYNAMIC","uriSpec":{"parts":[{"value":"scheme","variable":true},{"value":"://","variable":false},{"value":"address","variable":true},{"value":":","variable":false},{"value":"port","variable":true}]}}
```





should add this config in doc. if not set spring.cloud.zookeeper.discovery.prefer-ip-address=true, the default is false and register with hostname.
