### ISSUE TITLE
web-application-type none makes application register not working 

### ISSUE THREAD

**Issue by yhf597869822** [spring-cloud/spring-cloud-zookeeper#294]
**Describe the bug**
i set the web-application-type none, here is:
```
spring:
  main:
    web-application-type: none
  application:
    name: agent # Spring 应用名

  cloud:
    zookeeper:
      connect-string: 192.168.12.144:2182,192.168.12.145:2182,192.168.12.146:2182
      discovery:
        root: /service
        instance-port: 18081
```
then the application would not be registered , And don't find  in the zookeeper
![07CFEC5B-36EC-4BCF-918A-A83D4AA19D74](https://user-images.githubusercontent.com/31063160/132298367-e7d9f8ad-cc9a-4e40-bb4d-4b16432368ae.png)
The expect instance-name is `agent-192-168-12-144`

**Sample**
