### ISSUE TITLE
connectString property is ignored in bootstrap.yml

### ISSUE THREAD

**Issue by kupchenko** [spring-cloud/spring-cloud-zookeeper#309]
Is says here https://github.com/spring-cloud/spring-cloud-zookeeper/blob/main/docs/src/main/asciidoc/spring-cloud-zookeeper.adoc  :

`If you use [Spring Cloud Zookeeper Config], the values shown in the preceding example need to be in bootstrap.yml instead of application.yml.`

after configuring 'org.springframework.cloud:spring-cloud-starter-zookeeper-config' and adding connectString property to bootstrap.yml it still gets ignored and Curator tries to connect to localhost:2181 anyway.

However, if you configure it in a different way in regular application.yml file it works fine:

```yaml
zk:
  url: ${ZK_CLUSTER_URLS}
  path: /k8s/configuration/someservice
spring:
  config:
    import: "zookeeper://${zk.url}/${zk.path}"
```

The problem with this optional is that you can't specify list of zookeeper URLs.

**Comment by kupchenko** [comment]
In case somebody faces the same issue. Since spring cloud 2020, bootstrap dependency is served separately. So it order to make everything work you need to include `org.springframework.cloud:spring-cloud-starter-bootstrap` explicitly in you pox.xml/build.gradle. 
The config in `bootstrap.yml` would look like this:
```yaml
spring:
  cloud:
    zookeeper:
      connectString: ${ZK_CLUSTER_URLS}
      config:
        root: /configuration
        name: service
  config:
    import: "zookeeper:"
```
