### ISSUE TITLE
spring.cloud.zookeeper ConfigurationProperties can't be reset, always is localhost:2181

### ISSUE THREAD

**Issue by fengfei1000** [spring-cloud/spring-cloud-zookeeper#50]
```
spring:
  cloud:
    zookeeper:
      connectString: 172.16.0.212:2181
      enabled: true
      config:
        enabled: true
        root: configuration
        defaultContext: apps
        profileSeparator: ','


spring.cloud.zookeeper.connectString
spring.cloud.zookeeper.config.root
```

ConfigurationProperties can't be reset, always is localhost:2181
